### PR TITLE
change custom_set tests to use is_equal

### PR DESCRIPTION
**Pull request by bcpeinhardt**
We also have a test that verifies the is_equal functionality so this should be fine

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
There's no assertion now! Will need to add `assert True = ` to the start of each

**Comment by bcpeinhardt** [comment]
Whoops!!! Haha, will do when I can!

**Comment by bcpeinhardt** [comment]
Added the `let assert True` bits!

**Review by lpil — APPROVED** [review]
Thank you 💜

**Pull request merged**
