### PR TITLE
update test case for rna transcription

### PR DESCRIPTION
**Pull request by zhuangya**

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Hello! What's the motivation for this change?

**Comment by zhuangya** [comment]
Hi Louis @lpil, the reason I am raising this PR is that the name of this test case does not match its content, and it is also identical to the [next one](https://github.com/exercism/gleam/blob/5d83a6a061760df465a9c2aa7a96943e2aa9c684/exercises/practice/rna-transcription/test/rna_transcription_test.gleam#L15-L25).

**Comment by lpil** [comment]
Ah thank you! Does it now match what is specified in https://github.com/exercism/problem-specifications ?

**Comment by zhuangya** [comment]
@lpil yeah, totally. let me put a [spec ref](https://github.com/exercism/problem-specifications/blob/685ec55d9388937bbb3cc836b52b3ce27f208f37/exercises/rna-transcription/instructions.md) here for convenience

**Review by lpil — APPROVED** [review]
Thank you!

**Pull request merged**
