### PR TITLE
Remove extra []

### PR DESCRIPTION
**Pull request by lpil**

### CODE REVIEW

**Comment by iHiD** [comment]
Hey! Thanks. All the tracks seem to currently have this for all their badges (configlet and others). Do you know the reason that is current the case, and or what removing the extra [] changes? 

(cc @exercism/github-actions @ErikSchierboom)

**Comment by lpil** [comment]
It looks like a common markdown syntax error to me, but perhaps there's more to it

**Review by SaschaMann — APPROVED** [review]
I think the extra `[]` is a leftover from Travis, where the badge linked to a page that was different to the image url, e.g. `[Build Status](https://travis-ci.org/exercism/julia)`. 

Opening the image is not very useful, so perhaps you could consider adding a link to `https://github.com/exercism/gleam/actions?query=workflow%3Aconfiglet` or to the configlet repo when clicking on the badge.

**Comment by SaschaMann** [comment]
> All the tracks seem to currently have this for all their badges (configlet and others). 

@iHiD Tracks that have them and don't link to anything else should probably remove those, since it looks a bit wrong:

grafik

**Comment by iHiD** [comment]
I see! Thanks.

**Review by iHiD — APPROVED** [review]

**Comment by lpil** [comment]
Thanks all

**Comment by ErikSchierboom** [comment]
Thanks!

**Pull request merged**
