### PR TITLE
Updates help.md and tests.md

### PR DESCRIPTION
**Pull request by hsadia538**
@ErikSchierboom I have added the files and updated the content as well.

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Looks great! I didn't know about the stackoverflow section.

Might I also suggest the Discord? I think it will be the quickest place to get help. https://discord.gg/Fm8Pwmy

**Comment by hsadia538** [comment]
@lpil  I have added that as well. Thanks for the info

**Review by lpil — APPROVED** [review]
Thank you!

**Comment by ErikSchierboom** [comment]
Nice work!

**Comment by hsadia538** [comment]
Fixes: #58

**Pull request merged**
