### PR TITLE
pig-latin: add exercise

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
I don't understand the gleam format error:

```shell
erik@Eriks-MacBook-Pro-2 gleam % gleam format --check exercises/practice/pig-latin/.meta/example.gleam
erik@Eriks-MacBook-Pro-2 gleam % gleam --version
gleam 0.26.2
```

**Comment by jiegillet** [comment]
The CI is running 0.26.0 which seems to have a different (worse) formatter than 0.26.2
I'm running 0.26.0 locally so I committed the formatted file for now.
I guess we will have a few differences when we bump up the CI to 0.27.

**Review by jiegillet — APPROVED** [review]
Can't say that I love this one, but I do like your solution 👍

**Comment by ErikSchierboom** [comment]
I quite like the exercise. I also have a regex version: https://exercism.org/tracks/csharp/exercises/pig-latin/solutions/ErikSchierboom 😁

**Pull request merged**
