### PR TITLE
Update Gleam concepts: replace maps with dicts

### PR DESCRIPTION
**Pull request by Guria**
Follow up missed bits for faaed22

### CODE REVIEW

**Comment by Guria** [comment]
Note sure how concept rename could affect the course

**Review by lpil — COMMENTED** [review]
Brilliant! Thank you!

We'll need to also update the `config.json` file which declares and references the maps concept

**Comment by Guria** [comment]
updated

**Review by lpil — APPROVED** [review]
Thank you!!

**Pull request merged**
